aspnet/DataManager/AdavancedFunctionalities.md, aspnet/DropDownList/Getting-Started.md, aspnet/DropDownList/HowTo.md, aspnet/Grid/Data-Binding.md, aspnet/RadialMenu/item-customization.md
Worked on Bing report issues, merge these changes.
Regards,
Gowthaman
=> SEO-1973_Site_Audit_Issues

aspnet/Accordion/Getting-Started.md, aspnet/Barcode/Customizing-the-appearance.md, aspnet/Diagram/Localization.md, aspnet/WaitingPopUp/Getting-Started.md
Worked on Site Audit Issues, merge these changes.
Regards,
Gowthaman
=> SEO-2008_Site_Audit_Issues

aspnet/Chart/Data-Markers.md, aspnet/RichTextEditor/Getting-Started.md, aspnet/RichTextEditor/ImportAndExport.md, aspnet/Sparkline/Tooltip.md
Worked on Site Audit Bing report issues, merge these changes.
Regards,
Gowthaman
=> SEO-2111_Site_Audit_Issues

aspnet/Captcha/Getting-Started.md, aspnet/Chart/Legend.md, aspnet/Grid/How-to/Perform-Grid-Actions-on-External-button-click.md, aspnet/Numerictextbox/Getting-Started.md, aspnet/RadialSlider/image-customization.md
Worked on Site Audit Bing report issues, and merge these changes.
Regards,
Gowthaman
=> SEO-2245_Site_Audit_Issues

aspnet/Grid/Enable-Persistence.md, aspnet/Grid/Grid-Dependencies.md, aspnet/MaskeditTextbox/Configure-Persistence-Support.md
Worked on site audit issues, merge these changes.
Regards,
Gowthaman
=> SEO-2370_Site_Audit_Issues

aspnet/Licensing/how-to-register-in-an-application.md
Updated register licensing based on the issue reported by customer.
=> documentation(EJWEB-7102): Updated licensing

aspnet/Schedule/Server-side-events.md, aspnet/Schedule/keyboard-navigation.md
Worked on site audit Missing h1 tags issues, merge these changes,
Regards,
Gowthaman
=> SEO-2423_Site_Audit_Issues

aspnet/PivotChart/Chart-Types.md, aspnet/PivotChart/Server-side-events.md
Worked on Dropping Keywords changes, so merge these changes,
Regards,
Gowthaman
=> SEO-2472_Dropping_Keywords

aspnet/Diagram/Connector.md, aspnet/Diagram/Node.md
|Task Category| Pages With Redirect - Search console|
|:--|:--|
|Issue count| Help site links - 1000 |
|Fixed Count| Help site links - 5 |
|Analysis| Inspecting the links and found referring pages |
|Solution| replaced the exact URL instead of old URL |
|Hotfix PR| https://github.com/syncfusion-content/asp.netwebforms-docs/pull/260 | 
|Task link|https://syncfusion.atlassian.net/browse/SEO-2684|
|Excel| N/A |
Regards,
Gowthaman
=> SEO-2684-Coverage-Page-With-Redirect-UG

aspnet/CurrencyTextbox/Localization-Support.md, aspnet/CurrencyTextbox/RTL-Support.md, aspnet/Diagram/Connector.md
|Task Category| Pages With Redirect - Search console|
|:--|:--|
|Issue count| Help site links - 1000 |
|Fixed Count| Help site links - 3 |
|Analysis| Inspecting the links and found referring pages |
|Solution| replaced the exact URL instead of old URL |
|Hotfix PR| https://github.com/syncfusion-content/asp.netwebforms-docs/pull/270 | 
|Task link|https://syncfusion.atlassian.net/browse/SEO-2684|
|Excel| N/A |
Regards,
Gowthaman
=> SEO-2684-Coverage-report-pages-with-redirect

aspnet/DateTimePicker/Display-format.md, aspnet/ProgressBar/Define-value.md
Hi @ChristoIssac ,
Please review the changes for ASPNET Image Alt Text.
Regards,
Yvone.
=> SEO-2732 ASPNET Image Alt Text

aspnet/Diagram/Port.md
Hi Aishwarya,
Worked on page with redirect for help links, so merge these changes
Regards,
Gowthaman
=> SEO-3146-coverage-page-with-redirect-help

aspnet/Overview.md
Please review http to https link changes.
Regards,
Sharly A.
=> SEO-3108 - ASP.NET WebForm http to https

aspnet/Captcha/Enabling-Validation.md, aspnet/Overview.md
Please review changes for ASP.NET Webforms.
Regards,
Sharly A.
=> SEO-3222 - ASP.NET Webforms changes

aspnet/Chart/Exporting.md, aspnet/Grid/Columns.md, aspnet/Grid/Data-Binding.md, aspnet/Menu/Getting-Started.md, aspnet/Treegrid/Columns.md
Please review the changes for Page with redirect for ASP.NET.
Regards,
Yvone.
=> SEO-3239 ASP.NET Page with redirect

aspnet/Overview.md
Please review the changes for ASP.NET Overview.
Regards,
Sharly A.
=> SEO-3267 - ASP.NET Overview http to https changes

aspnet/Overview.md
Please review changes for ASP.NET WebForms overview.
Regards,
Sharly A.
=> SEO-3226 - ASP.NET WebForms

aspnet/ListView/Customize-Header.md, aspnet/ListView/Data-Binding.md, aspnet/ListView/VirtualScrolling.md
Worked on SEMrush issues, so merge these changes
Regards,
Gowthaman
=> SEO-3356-semrush-report-issues

aspnet/Chart/Trendlines.md, aspnet/ComboBox/DataBinding.md, aspnet/DropDownList/Rendering-Mode.md, aspnet/FileExplorer/How-To.md, aspnet/Treegrid/Searching.md
Renamed image alt text.
Regards,
Sharly A.
=> SEO-3353 - ASP.NET WebForms image alt text

aspnet/ListView/Data-Binding.md
Added redirect link for ASP.NET Webforms.
Regards,
Sharly A.
=> SEO-3446 - ASP.NET changes

aspnet/DataManager/Data-Binding.md, aspnet/Menu/Icons-and-navigating.md, aspnet/PivotClient/OLAP-Getting-Started.md, aspnet/PivotGrid/Styling.md, aspnet/Splitter/Appearance-and-Styling.md, aspnet/Treegrid/Rows.md
Please review the asp.net webform changes .
Regards,
Sharly A.
=> SEO-171911 - ASP.NET Webforms description is too long-short

aspnet/Chart/Chart-Series.md, aspnet/Gantt/Schedule-Modes.md, aspnet/SpreadSheet/Getting-Started.md
Have changed the redirect links, Please review.
Thanks.
Regards,
Edith.
=> SEO-172121-webforms-controls

aspnet/ListView/Data-Binding.md, aspnet/Overview.md
Please review ASP.NET WebForms changes.
Regards,
Sharly A.
=> SEO-172146 - ASP.NET WebForms

aspnet/Grid/Enable-Persistence.md
Hi @gowthamanthavasiyappan ,
Have worked on changing redirect links in ASP.NET.
Regards,
Yvone.
=> SEO-172160 ASP.NET Redirect

aspnet/Overview.md
Hi @MallikaRK ,
Have made the KB redirection link changes, please review.
Thanks.
Regards,
edith.
=> SEO-172121-ASP.NET-webforms-redirect-weblinks

aspnet/Chart/Overview.md, aspnet/DataManager/Data-Binding.md, aspnet/Slider/Getting-Started.md
Hi @MallikaRK,
Worked on description too long / short.
Regards,
Sharly A.
=> SEO-172159 - ASP.NET WebForms description too long / short

aspnet/Grid/Data-Adaptors.md, aspnet/Grid/Exporting.md, aspnet/Grid/Style-and-Appearance.md, aspnet/UploadBox/File-Size.md
Have changed ASPNET Page with Redirect UG.
Regards,
Yvone.
=> SEO-175659 ASPNET Page with Redirect

aspnet/Chart/Legend.md, aspnet/Diagram/Automatic-Layout.md, aspnet/Grid/Editing.md, aspnet/Installation/web-installer/how-to-download.md, aspnet/TreeView/Populate-Data.md, aspnet/WaitingPopUp/Getting-Started.md
Have worked on changing Page with Redirect links.
Regards,
Yvone.
=> SEO-176130 ASPNET Page Redirect

aspnet/DateTimePicker/Getting-Started.md
Hello,
Worked on the links with redirects.
Regards,
Beryl.
=> SEO-175653-ASPNET-Pages-With-Redirects

aspnet/Chart/Exporting.md
Hello,
I have worked on links with redirects.
Kind regards,
Beryl.
=> SEO-177279-Page-With-Redirect-ASPNET

aspnet/Captcha/Getting-Started.md
Have changed Page with Redirect links.
Regards,
Yvone.
=> SEO-178113 ASPNET Page with Redirect

aspnet/DatePicker/Getting-Started.md, aspnet/Grid/Data-Binding.md, aspnet/Installation/Installation-Errors.md
Hello,
I have worked on links with redirects.
Regards,
Beryl.
=> SEO-179239-Redirect-Links-Webforms

aspnet/Grid/How-to/Change-background-color-of-a-row-using-rowDataBound-event.md
Have worked on changing title and description in ASP.NET Web Forms controls, please review.
Regards,
Yvone.
=> SEO-181951 ASP.NET Title Identical

aspnet/Grid/How-to/Custom-Binding-for-Grid-CRUD-operation.md, aspnet/PdfViewer/Supported-and-Unsupported-Elements.md
Have worked on missing H1, please review.
Regards,
Yvone.
=> SEO-183463 ASP.NET Missing H1

aspnet/Overview.md
Updated Overview UG documentation for ASP.NET Web Forms.
=> Update ASP.NET Web Forms Overview page

aspnet/SpreadSheet/Editing.md
Hi @GowthamanMayil,
Please review the below PR,
Title | Description
-- | --
Task Category | Permanent Redirect|
Content Task Link/Mail Screenshot | NA|
|Hotfix |https://github.com/syncfusion-content/javascript-docs/pull/506|
Ticket/Task link |https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/188023|
|Changes Made | Reason for change |
|-- | -- |
|Changed redirect links| To avoid redirect links |
Regards,
Yvone.
=> SEO-187686 ASPNET Permanent Redirect

aspnet/DateRangePicker/customization.md
Please review the below PR,
Title | Description
-- | --
Task Category | Missing H1 |
Content Task Link/Mail Screenshot | NA|
|Hotfix |https://github.com/syncfusion-content/asp.netwebforms-docs/pull/549|
Ticket/Task link |https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/187685/|
|Changes Made | Reason for change |
|-- | -- |
|Missing H1| To avoid multiple H1 and improve user experience |
Regards,
Yvone.
=> SEO-187685 ASPNET Missing H1

aspnet/DateRangePicker/display-format.md
Hi @Yvone-Atieno  
|Title|Description|
|--|--|
|Task Category| Site Audit
|Content Task Link/Mail Screenshot| NA|
|UX task| NA|
|Hotfix|https://github.com/syncfusion-content/asp.netwebforms-docs/pull/566
|Ticket/Task link| https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/191916|
|Excel/SharePoint link| NA|
|Changes made|Reason for changes|
|--|--|
|updated valid links| To solve redirection link
Regards,
Mercy A.
=> SEO-191916-ASP.NET-DaterangerPicker-Site-audit
